name: Default Node 14

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "Crucible-Standard/obiter-dictum" . . .
        run: docker build -t Crucible-Standard/obiter-dictum
      - name: Run The Linter . . .
        run: docker run Crucible-Standard/obiter-dictum npm run test:lint
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "crucible-standard/obiter-dictum" . . .
        run: docker build -t crucible-standard/obiter-dictum
      - name: Run The Tests . . .
        run: docker run crucible-standard/obiter-dictum npm run test

